### PR TITLE
WIP Removes csrf from API routes

### PR DESCRIPTION
**Pull request by Pr0x1m4**
From #55 in order to facilitate a `hashbase-cli` api routes have been registered before csrf middleware

### CODE REVIEW

**Comment by Pr0x1m4** [comment]
So after realizing that prefixing api routes with `/api` means that all the references to `/v1/route` (in page views and js files) would have to change, I reverted tests and just prefixed api routes with `/v1/` instead

**Comment by pfrazee** [comment]
I appreciate the PR, but I can't accept it because you have a code formatter making unrelated changes. Can you create another PR without the formatter? If not, I can make a PR this week sometime.

**Comment by Pr0x1m4** [comment]
Removed the code formatter sections, sorry about that :sweat_smile:

**Comment by pfrazee** [comment]
Appreciate it! I'll test this out and merge today or tomorrow.

**Comment by pfrazee** [comment]
Merged and deploying

**Pull request merged**
